### ISSUE TITLE
Plugin attempts to retrieve MFA with every run

### ISSUE THREAD

**Issue by earchibald-lv** [xeger/awsume-1password-plugin#1]
**Describe the bug**
Plugin attempts to retrieve the MFA with each run. The MFA is still cached by awsume, and if I cancel the plugin auth awsume still functions properly,

**Expected behavior**
The plugin should not request 1Password auth if the MFA is cached by awsume

**Output**
Invoke `awsume` with the `--debug` flag and paste the resulting output below. Make sure to include the command you ran, with all of the flags. If the program crashed then make sure to include the stack trace and all relevant error messages.

```
❯ awsume sre-team@lv-tst2
1Password: error initializing client: authorization prompt dismissed, please try again

Session token will expire at 2023-08-29 20:58:35
[sre-team@lv-tst2] Role credentials will expire 2023-08-29 16:03:39
```

**Configuration**
If relevant, please share your AWSume configuration file below. This file should be free of secrets, but please verify before submitting your report.

```yaml
1password: aws_lv-techops_earchibald
colors: true
console:
  browser:
    command: ''
  browser_command: ''
fuzzy-match: true
role-duration: 0
role-session-name: earchibald
```

**Additional context**
